travis:
  secure:
    BINSTAR_TOKEN: jx1Q8JiiEJ8yP2Ldp1mVAyGN/cI9t5/V52coEGMT38guJwvQ8u9Lq64PHhZ5sPQLB/96RbLgs0k6XItlZmph9KUwagDcqrABnly3IIYhW8/x7Da1+4Zzg1Sm2+zpza11iJZaIGxZ5nnpJyGEGS9eOWYq6Zlr7eA7Ss15swzETOlViMSmpOu3DziHSZR7Gz3ZYolf106a9pjp09lQoGVQ5G/gjbk+G0h9ojq94z+Vh3WQ75v2XFYHyu98gT/5dwbsMB4TtiPD0S2IazDNN1kkWCHF6GXaGDBmxaeaONObzpKbzHOgAR0x+ZA6vzbeVM8Jv+2A2WXccqSwywasBE0rFTS2WmlOsWub/c5E1+tlsC7iRswz+cgLpME+yQizNYIwj4zL4RD6jzuVpA1kaqB+Se21gU6O000h/kfUQ0LH8UZD3GzLbiblAjJijwVf6hwbSGXGe95OvNij2RUmeRYXZAaCbS18p77kMyfeiOHS/eN+Dvz/7dQC6PLHn73TxkjMrcDout2p4M06hgV2flGzNwwfK6mf3E24IIWRc453vw5SCGhJSLnZLXWvKCFCuSnoHbsxbCY1FSxezqFx2dQBZUTalAT3FnWu8wc2D4hQeEd3AVXLDvRMjDvJH45G22PdfCgt4129qaBxtb8uakTotBdosTe4Q73rmvbSwi3feTU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
